
name: Destroy Infra

on:
  workflow_dispatch: #Permite hacerlo de forma manual, no autom√°tica.
  
    
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Emitir y firmar token OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::151098958427:role/GithubActionsOIDC
          aws-region: eu-east-1          
      - name: Clonar Repo en la MV
        uses: actions/checkout@v4

      - name: Instalar terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Destruir infra en AWS
        run: |
         cd terraform
         terraform init
         terraform destroy -auto-approve
 
