
name: Destroy Infra

on:
  push:

  workflow_dispatch: #Permite hacerlo de forma manual, no autom√°tica.
  
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repo en la MV
        uses: actions/checkout@v4

      - name: Instalar terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Destruir infra en AWS
        run: |
         cd terraform
         terraform destroy -auto-approve
 
